#!/usr/bin/env python

data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

import aocd
data = aocd.data

def line_by_line(data: str):
    lines = data.splitlines()
    values = [int(c=="S") for c in lines[0]]

    for line in lines[1:]:
        for i in range(len(line)):
            if line[i] == "^":
                values[i-1] += values[i]
                values[i+1] += values[i]
                values[i] = 0

    return values

print(sum(line_by_line(data)))

